/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ai.cellwars;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author frikkie
 */
public class BoardUI extends javax.swing.JFrame {
    Integer n;
    Boolean selected;
    Integer selectedX;
    Integer selectedY;
    Board gameBoard;
    
    /**
     * Creates new form BoardUI
     */
    public BoardUI() {
        initComponents();
        n = 8;
        selected = false;
        selectedX = -1;
        selectedY = -1;
    }
    
    /**
     * Creates new form BoardUI
     */
    public BoardUI(Integer n) {
        initComponents();
        this.n = n;
        selected = false;
        selectedX = -1;
        selectedY = -1;
        
        DefaultTableModel dtm = (DefaultTableModel) tblBoard.getModel();
        dtm.setRowCount(n);
        dtm.setColumnCount(n);
        tblBoard.setModel(dtm);
        tblBoard.setShowGrid(true);
        for (int i = 0; i < n; ++i){
            tblBoard.setRowHeight(i,520/n);
        }
    }
    
    public javax.swing.JTable getTable(){
        return this.tblBoard;
    }
    
    public void setBoard(Board gameBoard) {
        this.gameBoard = gameBoard;
    }
    
    public void setTable(javax.swing.JTable table){
        tblBoard = table;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBoard = new javax.swing.JTable();

        tblBoard.setBorder(new javax.swing.border.MatteBorder(null));
        tblBoard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBoard.setAutoscrolls(false);
        tblBoard.setCellSelectionEnabled(true);
        tblBoard.setFocusable(false);
        tblBoard.setTableHeader(null);
        tblBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBoardMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBoard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 915, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBoardMouseClicked
        // TODO add your handling code here:
        Integer x = tblBoard.getSelectedColumn();
        Integer y = tblBoard.getSelectedRow();
        
        if (!selected) {
            if (!(gameBoard.getBlockType(x, y) != null && (gameBoard.getBlockType(x, y).equals(BlockType.BLUE_OCCUPIED) || gameBoard.getBlockType(x, y).equals(BlockType.RED_OCCUPIED)))) {
                selected = false;
                selectedX = -1;
                selectedY = -1;
                tblBoard.clearSelection();
            }
            else {
                selected = true;
                selectedX = x;
                selectedY = y;

            }
        }
        else {
            
        }
    }//GEN-LAST:event_tblBoardMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BoardUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBoard;
    // End of variables declaration//GEN-END:variables
}
